import { c as create_ssr_component, e as escape, b as null_to_empty, v as validate_component } from "../../chunks/ssr.js";
const Header_svelte_svelte_type_style_lang = "";
const css = {
  code: ".navbar-animation.svelte-165ebyy.svelte-165ebyy{animation:svelte-165ebyy-navbar 0.5s alternate;background-color:#1a1a1a;color:#fff}@keyframes svelte-165ebyy-navbar{from{top:-50px}to{top:0px}}#menuButton.svelte-165ebyy.svelte-165ebyy{display:none}@media only screen and (max-width: 891px){#menuButton.svelte-165ebyy.svelte-165ebyy{display:inline-block}.menus.svelte-165ebyy.svelte-165ebyy{position:absolute;width:100vw;top:100%;left:0;background-color:white;flex-direction:column;padding:20px 0;box-shadow:1px 1px 5px #dadada}.menus.svelte-165ebyy>.sub-menu.svelte-165ebyy{flex-direction:column;margin:0}.menus.svelte-165ebyy .flex ul.svelte-165ebyy{flex-direction:column;width:100%;align-items:center;margin-bottom:10px}.menus.svelte-165ebyy .flex ul li.svelte-165ebyy{width:100%;text-align:center}.menus.svelte-165ebyy .flex ul li a.svelte-165ebyy{color:#1a1a1a;width:100%;display:inline-block;padding:5px 0}.menus.svelte-165ebyy .flex ul li a.svelte-165ebyy:hover{background-color:#ff3a54;color:#fff}.menus.svelte-165ebyy .call-btn-div.svelte-165ebyy{padding-top:10px;align-items:center;justify-content:center}}",
  map: null
};
const Header = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  $$result.css.add(css);
  return `<section class="${escape(null_to_empty(`${"relative"} top-0 bg-white z-50 shadow-sm relative`), true) + " svelte-165ebyy"}"><div class="flex justify-between px-6 py-3 items-center font-mukta"><div class="logo" data-svelte-h="svelte-1pbbqzm"><a href="/" class="svelte-165ebyy"> <h1 class="text-3xl font-bold font-mukta">Fixonn<span class="text-logoIcon">.</span></h1></a></div> <button id="menuButton" class="outline-none text-xl text-logoIcon active:text-black ease-in duration-150 svelte-165ebyy" data-svelte-h="svelte-14yi1jn"><i id="subMenuToggleButton" class="fas fa-bars"></i></button> ${``}</div> </section>`;
});
const Footer = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  return `<footer class="bg-white text-black"><div class="container mx-auto max-w-c-1390 font-mukta pt-12"><div class="flex flex-wrap lg:flex-nowrap lg:gap-x-16 mx-4"><div class="w-full md:w-1/2 lg:w-1/4 mb-6" data-svelte-h="svelte-1xxw9a9"><div class="mb-4"><img src="../images/logo.jpeg" alt="Logo" class="w-20 h-20 rounded-full"></div> <p class="text-lightText text-md">Your company&#39;s mission statement or a brief description can
                    go here. Lorem ipsum dolor sit amet consectetur adipisicing
                    elit. Ipsa nesciunt perspiciatis, ipsum harum neque officia!</p></div>  <div class="w-full md:w-1/2 lg:w-1/4 mb-6"><h3 class="text-xl font-semibold mb-4" data-svelte-h="svelte-1vbt458">Services</h3> <ul class="text-lightText"><li class="mb-2"><a class="hover:text-black hover:pl-2 ease-in duration-300" href="/services/plumbing" data-svelte-h="svelte-13fa2tp"><i class="fa-solid fa-chevron-right text-xs mr-2"></i> Plumbing</a></li> <li class="mb-2"><a class="hover:text-black hover:pl-2 ease-in duration-300" href="/services/electrical" data-svelte-h="svelte-1xdq49j"><i class="fa-solid fa-chevron-right text-xs mr-2"></i> Electrical</a></li> <li class="mb-2"><a class="hover:text-black hover:pl-2 ease-in duration-300" href="/services/pest-control" data-svelte-h="svelte-1e9cxgq"><i class="fa-solid fa-chevron-right text-xs mr-2"></i> Pest Control</a></li> <li class="mb-2"><a class="hover:text-black hover:pl-2 ease-in duration-300" href="/services/deep-cleaning" data-svelte-h="svelte-1gkypu8"><i class="fa-solid fa-chevron-right text-xs mr-2"></i> Deep Cleaning</a></li> <li class="mb-2"><a class="hover:text-black hover:pl-2 ease-in duration-300" href="/services/painting" data-svelte-h="svelte-1r661kp"><i class="fa-solid fa-chevron-right text-xs mr-2"></i> Painting</a></li> <li class="mb-2"><a class="hover:text-black hover:pl-2 ease-in duration-300" href="/services/carpentry" data-svelte-h="svelte-1e5kuqz"><i class="fa-solid fa-chevron-right text-xs mr-2"></i> Carpentry</a></li></ul></div>  <div class="w-full md:w-1/2 lg:w-1/4 mb-6" data-svelte-h="svelte-lom09b"><h3 class="text-xl font-semibold mb-4">Contact</h3> <ul class="text-lightText"><li class="mb-2"><a class="hover:text-black ease-in duration-300" href="mailto:your@example.com"><i class="fa-solid fa-envelope text-sm mr-2"></i> your@example.com</a></li> <li class="mb-2"><a class="hover:text-black ease-in duration-300" href="tel:+919998705371"><i class="fa-solid fa-phone text-sm mr-2"></i> (123) 456-7890</a></li> <li class="mb-2"><i class="fa-solid fa-location-dot text-sm mr-2"></i> 123 Street
                        Name, City</li></ul></div>  <div class="w-full md:w-1/2 lg:w-1/4 mb-6" data-svelte-h="svelte-4fmn4k"><h3 class="text-xl font-semibold mb-4">Links</h3> <ul class="text-lightText"><li class="mb-2"><a href="/" class="hover:text-black hover:pl-2 ease-in duration-300"><i class="fa-solid fa-chevron-right text-xs mr-2"></i> Home</a></li> <li class="mb-2"><a href="/about" class="hover:text-black hover:pl-2 ease-in duration-300"><i class="fa-solid fa-chevron-right text-xs mr-2"></i> About</a></li> <li class="mb-2"><a href="/#services" class="hover:text-black hover:pl-2 ease-in duration-300"><i class="fa-solid fa-chevron-right text-xs mr-2"></i> Services</a></li> <li class="mb-2"><a href="/" class="hover:text-black hover:pl-2 ease-in duration-300"><i class="fa-solid fa-chevron-right text-xs mr-2"></i> Careers</a></li> <li class="mb-2"><a href="/contact" class="hover:text-black hover:pl-2 ease-in duration-300"><i class="fa-solid fa-chevron-right text-xs mr-2"></i> Contact Us</a></li></ul></div></div></div> <div class="w-full mx-auto max-w-c-1390 font-mukta border-t border-[#e0e0e0] p-4 text-lightText" data-svelte-h="svelte-1a0ljhb"><div class="flex justify-between items-center"><p class="text-opacity-75">© Fixonn 2023, All Rights Reserved</p> <div class="space-x-4"><a href="https://facebook.com/" class="text-opacity-75 hover:text-logoIcon ease-in duration-150"><i class="fab fa-facebook-f"></i></a> <a href="https://twitter.com/" class="text-opacity-75 hover:text-logoIcon ease-in duration-150"><i class="fab fa-twitter"></i></a> <a href="https://instagram.com/" class="text-opacity-75 hover:text-logoIcon ease-in duration-150"><i class="fab fa-instagram"></i></a></div></div></div></footer>`;
});
const index = "";
const Layout = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  return `<main>${validate_component(Header, "Header").$$render($$result, {}, {}, {})} ${slots.default ? slots.default({}) : ``} ${validate_component(Footer, "Footer").$$render($$result, {}, {}, {})}</main>`;
});
export {
  Layout as default
};
