import { c as create_ssr_component, e as escape, b as null_to_empty, v as validate_component } from "../../chunks/ssr.js";
const Header_svelte_svelte_type_style_lang = "";
const css = {
  code: ".navbar-animation.svelte-1aw3300{animation:svelte-1aw3300-navbar 0.5s alternate;background-color:#1a1a1a;color:#fff}@keyframes svelte-1aw3300-navbar{from{top:-50px}to{top:0px}}",
  map: null
};
const Header = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  $$result.css.add(css);
  return `<section class="${escape(null_to_empty(`${"relative"} top-0 bg-white z-50 shadow-sm`), true) + " svelte-1aw3300"}"><div class="flex justify-between px-6 py-3 items-center font-mukta" data-svelte-h="svelte-aaou98"><div class="logo"><a href="/"> <h1 class="text-3xl font-bold font-mukta">Fixonn<span class="text-logoIcon">.</span></h1></a></div> <div class="menus flex"><div class="flex items-center mr-8"><ul class="flex gap-x-8 font-regular"><li><a href="/" class="font-normal hover:text-logoIcon ease-in duration-150">Home</a></li> <li><a href="/about" class="font-normal hover:text-logoIcon ease-in duration-150">About Us</a></li> <li><a href="/#services" class="font-normal hover:text-logoIcon ease-in duration-150">Services</a></li> <li><a href="/careers" class="font-normal hover:text-logoIcon ease-in duration-150">Careers</a></li> <li><a href="/contact" class="font-normal hover:text-logoIcon ease-in duration-150">Contact Us</a></li></ul></div> <div><a class="bg-logoIcon text-white flex px-4 py-3 rounded" href="tel:9998705371"><span class="material-icons mr-2">call</span> Call Us Now</a></div></div></div> </section>`;
});
const Footer = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  return `<footer class="bg-white text-black"><div class="container mx-auto max-w-c-1390 font-mukta mb-10 pt-12"><div class="flex flex-wrap lg:flex-nowrap lg:gap-x-16 mx-4"><div class="w-full md:w-1/2 lg:w-1/4 mb-6" data-svelte-h="svelte-1xxw9a9"><div class="mb-4"><img src="../images/logo.jpeg" alt="Logo" class="w-20 h-20 rounded-full"></div> <p class="text-lightText text-md">Your company&#39;s mission statement or a brief description can
                    go here. Lorem ipsum dolor sit amet consectetur adipisicing
                    elit. Ipsa nesciunt perspiciatis, ipsum harum neque officia!</p></div>  <div class="w-full md:w-1/2 lg:w-1/4 mb-6"><h3 class="text-xl font-semibold mb-4" data-svelte-h="svelte-1vbt458">Services</h3> <ul class="text-lightText"><li class="mb-2"><a class="hover:text-black hover:pl-2 ease-in duration-300" href="/services/plumbing" data-svelte-h="svelte-13fa2tp"><i class="fa-solid fa-chevron-right text-xs mr-2"></i> Plumbing</a></li> <li class="mb-2"><a class="hover:text-black hover:pl-2 ease-in duration-300" href="/services/electrical" data-svelte-h="svelte-1xdq49j"><i class="fa-solid fa-chevron-right text-xs mr-2"></i> Electrical</a></li> <li class="mb-2"><a class="hover:text-black hover:pl-2 ease-in duration-300" href="/services/pest-control" data-svelte-h="svelte-1e9cxgq"><i class="fa-solid fa-chevron-right text-xs mr-2"></i> Pest Control</a></li> <li class="mb-2"><a class="hover:text-black hover:pl-2 ease-in duration-300" href="/services/deep-cleaning" data-svelte-h="svelte-1gkypu8"><i class="fa-solid fa-chevron-right text-xs mr-2"></i> Deep Cleaning</a></li> <li class="mb-2"><a class="hover:text-black hover:pl-2 ease-in duration-300" href="/services/painting" data-svelte-h="svelte-1r661kp"><i class="fa-solid fa-chevron-right text-xs mr-2"></i> Painting</a></li> <li class="mb-2"><a class="hover:text-black hover:pl-2 ease-in duration-300" href="/services/carpentry" data-svelte-h="svelte-1e5kuqz"><i class="fa-solid fa-chevron-right text-xs mr-2"></i> Carpentry</a></li></ul></div>  <div class="w-full md:w-1/2 lg:w-1/4 mb-6" data-svelte-h="svelte-lom09b"><h3 class="text-xl font-semibold mb-4">Contact</h3> <ul class="text-lightText"><li class="mb-2"><a class="hover:text-black ease-in duration-300" href="mailto:your@example.com"><i class="fa-solid fa-envelope text-sm mr-2"></i> your@example.com</a></li> <li class="mb-2"><a class="hover:text-black ease-in duration-300" href="tel:+919998705371"><i class="fa-solid fa-phone text-sm mr-2"></i> (123) 456-7890</a></li> <li class="mb-2"><i class="fa-solid fa-location-dot text-sm mr-2"></i> 123 Street
                        Name, City</li></ul></div>  <div class="w-full md:w-1/2 lg:w-1/4 mb-6" data-svelte-h="svelte-o6cqdh"><h3 class="text-xl font-semibold mb-4">Links</h3> <ul class="text-lightText"><li class="mb-2"><a href="/" class="hover:text-black hover:pl-2 ease-in duration-300"><i class="fa-solid fa-chevron-right text-xs mr-2"></i> Home</a></li> <li class="mb-2"><a href="/about" class="hover:text-black hover:pl-2 ease-in duration-300"><i class="fa-solid fa-chevron-right text-xs mr-2"></i> About</a></li> <li class="mb-2"><a href="/#services" class="hover:text-black hover:pl-2 ease-in duration-300"><i class="fa-solid fa-chevron-right text-xs mr-2"></i> Services</a></li> <li class="mb-2"><a href="/careers" class="hover:text-black hover:pl-2 ease-in duration-300"><i class="fa-solid fa-chevron-right text-xs mr-2"></i> Careers</a></li> <li class="mb-2"><a href="/contact" class="hover:text-black hover:pl-2 ease-in duration-300"><i class="fa-solid fa-chevron-right text-xs mr-2"></i> Contact Us</a></li></ul></div></div></div> <div class="w-full mx-auto max-w-c-1390 font-mukta border-t border-[#e0e0e0] py-4 text-lightText" data-svelte-h="svelte-70kqxk"><div class="flex justify-between items-center"><p class="text-opacity-75">© Fixonn 2023, All Rights Reserved</p> <div class="space-x-4"><a href="https://facebook.com/" class="text-opacity-75 hover:text-logoIcon ease-in duration-150"><i class="fab fa-facebook-f"></i></a> <a href="https://twitter.com/" class="text-opacity-75 hover:text-logoIcon ease-in duration-150"><i class="fab fa-twitter"></i></a> <a href="https://instagram.com/" class="text-opacity-75 hover:text-logoIcon ease-in duration-150"><i class="fab fa-instagram"></i></a></div></div></div></footer>`;
});
const index = "";
const Layout = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  return `<main>${validate_component(Header, "Header").$$render($$result, {}, {}, {})} ${slots.default ? slots.default({}) : ``} ${validate_component(Footer, "Footer").$$render($$result, {}, {}, {})}</main>`;
});
export {
  Layout as default
};
