import { c as create_ssr_component, v as validate_component } from "../../../chunks/ssr.js";
import { B as BackToTop, C as ContactIcons } from "../../../chunks/ContactIcons.js";
const _page_svelte_svelte_type_style_lang = "";
const css = {
  code: '#contactUsIntro.svelte-9klit5{background-image:linear-gradient(\r\n                rgba(19, 40, 76, 0.775),\r\n                rgba(19, 40, 76, 0.322)\r\n            ),\r\n            url("../images/businessman-big-office.jpg");background-position:center;background-size:cover}',
  map: null
};
const Page = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  $$result.css.add(css);
  return `${$$result.head += `<!-- HEAD_svelte-14d28y4_START -->${$$result.title = `<title>Contact Us - Fixonn</title>`, ""}<!-- HEAD_svelte-14d28y4_END -->`, ""} <section id="contactUsIntro" class="py-32 svelte-9klit5" data-svelte-h="svelte-cvf597"><div class="font-mukta flex flex-col items-center animate_bottom"><h3 class="text-logoIcon font-bold w-fit">CONTACT US</h3> <h1 class="mt-4 text-5xl font-semibold text-white">Reach out to Fixonn</h1></div></section> <section id="contactUs" data-svelte-h="svelte-swerfw"><div class="font-mukta mx-auto max-w-c-1390 px-6 py-20 border-b border-[#E0E0E0]"><div class="font-mukta flex flex-col items-center animate_bottom"><h3 class="text-logoIcon font-bold w-fit">CONTACT US</h3> <h1 class="my-4 text-5xl font-semibold text-black">Let us Know how we can help you?</h1> <p class="w-1/2 text-center text-[#757693]">Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero
                eligendi, velit, neque deserunt ipsam quod, voluptatum minima
                corrupti mollitia maiores ex unde magnam quis reiciendis?</p></div>  <div class="mt-20"><div class="grid grid-cols-3 gap-8"><div class="animate_bottom mb-2 p-4 flex justify-center items-center border border-[#E0E0E0] rounded-md text-lg text-[#757693]"><i class="fa-solid fa-envelope text-sm mr-2"></i> your@example.com</div> <div class="animate_bottom mb-2 p-4 flex justify-center items-center border border-[#E0E0E0] rounded-md text-lg text-[#757693]"><i class="fa-solid fa-phone text-sm mr-2"></i> (123) 456-7890</div> <div class="animate_bottom mb-2 p-4 flex justify-center items-center border border-[#E0E0E0] rounded-md text-lg text-[#757693]"><i class="fa-solid fa-location-dot text-sm mr-2"></i> 123 Street
                    Name, City</div></div> <div class="mt-20 flex"><div class="w-1/2 animate_left"><div class="px-20"><img class="h-full" src="../images/3969587.jpg" alt="Contact Us"></div></div> <div class="w-1/2 animate_right"><div class="mb-10"><h1 class="text-3xl text-black mb-4">Let us know if you have anything to share with us.</h1></div> <form class="flex flex-col gap-y-4"><div class="flex gap-x-4"><input placeholder="Enter your name" type="text" class="w-1/2 rounded-md p-3 border border-[#E0E0E0]"> <input placeholder="Enter your email" type="email" class="w-1/2 rounded-md p-3 border border-[#E0E0E0]"></div> <div class="flex gap-x-4"><input placeholder="Enter your subject (optional)" type="text" class="w-1/2 rounded-md p-3 border border-[#E0E0E0]"> <input placeholder="Enter your phone (optional)" type="text" class="w-1/2 rounded-md p-3 border border-[#E0E0E0]"></div> <div><textarea placeholder="Enter your message..." class="w-full rounded-md p-3 border border-[#E0E0E0]" rows="6"></textarea></div> <div><button class="bg-logoIcon text-white rounded-md py-3 px-4" type="submit">Send Message <i class="ml-2 fa fa-arrow-right"></i></button></div></form></div></div></div></div></section>  ${validate_component(BackToTop, "BackToTop").$$render($$result, { pathName: "/contact" }, {}, {})} ${validate_component(ContactIcons, "ContactIcons").$$render($$result, {}, {}, {})}`;
});
export {
  Page as default
};
