import { c as create_ssr_component, v as validate_component } from "../../../chunks/ssr.js";
import { B as BackToTop, C as ContactIcons } from "../../../chunks/ContactIcons.js";
const _page_svelte_svelte_type_style_lang = "";
const css = {
  code: '#contactUsIntro.svelte-9klit5{background-image:linear-gradient(\r\n                rgba(19, 40, 76, 0.775),\r\n                rgba(19, 40, 76, 0.322)\r\n            ),\r\n            url("../images/businessman-big-office.jpg");background-position:center;background-size:cover}',
  map: null
};
const Page = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  $$result.css.add(css);
  return `${$$result.head += `<!-- HEAD_svelte-14d28y4_START -->${$$result.title = `<title>Contact Us - Fixonn</title>`, ""}<!-- HEAD_svelte-14d28y4_END -->`, ""} <section id="contactUsIntro" class="py-20 md:py-32 svelte-9klit5" data-svelte-h="svelte-10430ko"><div class="font-mukta flex flex-col items-center animate_bottom"><h3 class="text-logoIcon font-bold w-fit">CONTACT US</h3> <h1 class="mt-4 text-3xl md:text-5xl font-semibold text-white">Reach out to Fixonn</h1></div></section> <section id="contactUs" data-svelte-h="svelte-zg0s24"><div class="font-mukta mx-auto max-w-c-1390 px-4 md:px-6 py-10 md:py-20 border-b border-[#E0E0E0]"><div class="font-mukta flex flex-col items-center animate_bottom"><h3 class="text-logoIcon font-bold w-fit">CONTACT US</h3> <h1 class="my-4 text-3xl text-center md:text-5xl font-semibold text-black">Let us Know how we can help you?</h1> <p class="md:w-1/2 text-center text-[#757693]">Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero
                eligendi, velit, neque deserunt ipsam quod, voluptatum minima
                corrupti mollitia maiores ex unde magnam quis reiciendis?</p></div>  <div class="mt-10 md:mt-20"><div class="grid gap-2 md:grid-cols-3 md:gap-8"><div class="animate_bottom mb-2 p-3 md:p-4 flex justify-center items-center border border-[#E0E0E0] rounded-md text-lg text-[#757693]"><i class="fa-solid fa-envelope text-sm mr-2"></i> your@example.com</div> <div class="animate_bottom mb-2 p-3 md:p-4 flex justify-center items-center border border-[#E0E0E0] rounded-md text-lg text-[#757693]"><i class="fa-solid fa-phone text-sm mr-2"></i> (123) 456-7890</div> <div class="animate_bottom mb-2 p-3 md:p-4 flex justify-center items-center border border-[#E0E0E0] rounded-md text-lg text-[#757693]"><i class="fa-solid fa-location-dot text-sm mr-2"></i> 123 Street
                    Name, City</div></div> <div class="mt-0 md:mt-20 grid md:grid-cols-2"><div class="animate_left"><div class="md:px-20"><img class="h-full" src="../images/3969587.jpg" alt="Contact Us"></div></div> <div class="animate_right"><div class="mb-4 md:mb-10"><h1 class="text-semibold text-2xl md:text-3xl text-black">Let us know if you have anything to share with us.</h1></div> <form name="contact" method="POST" data-netlify="true" class="flex flex-col gap-y-4" data-netlify-honeypot="bot-field"><input type="hidden" name="bot-field"> <div class="flex flex-col sm:flex-row gap-4"><input name="name" placeholder="Enter your name" type="text" class="sm:w-1/2 rounded-md p-3 border border-[#E0E0E0]" required> <input name="email" placeholder="Enter your email" type="email" class="sm:w-1/2 rounded-md p-3 border border-[#E0E0E0]" required></div> <div class="flex flex-col sm:flex-row gap-4"><input name="subject" placeholder="Enter your subject (optional)" type="text" class="sm:w-1/2 rounded-md p-3 border border-[#E0E0E0]"> <input name="phone" placeholder="Enter your phone (optional)" type="text" class="sm:w-1/2 rounded-md p-3 border border-[#E0E0E0]"></div> <div><textarea name="message" placeholder="Enter your message..." class="w-full rounded-md p-3 border border-[#E0E0E0]" rows="6" required></textarea></div> <div><button class="bg-logoIcon text-white rounded-md py-3 px-4" type="submit">Send Message <i class="ml-2 fa fa-arrow-right"></i></button></div></form></div></div></div></div></section>  ${validate_component(BackToTop, "BackToTop").$$render($$result, { pathName: "/contact" }, {}, {})} ${validate_component(ContactIcons, "ContactIcons").$$render($$result, {}, {}, {})}`;
});
export {
  Page as default
};
